#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# standard pkgin update:
pkg_admin rebuild
pkgin -y up
pkgin -y clean

echo "* Create rsyslog.d folder for extra configuration files"
mkdir -p /opt/local/etc/rsyslog.d

# Clean up
echo "* Cleaning up."
rm -rf /root/*
rm -rf /tmp/*

# Prepare image for provisioning
sm-prepare-image -y
