#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nginx_request
	nginx_status
	haproxy_
	haproxy_ng
  proftpd
	proftpd_bytes
	proftpd_count
"

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# standard pkgin update:
pkg_admin rebuild
pkgin -y up
pkgin -y clean

echo "* Create users & groups"
groupadd -g 1000 inet
useradd -g www ssh
useradd -d /ftp/rsync -c "Weewx backup subdir" -g inet rsync

echo "* Create rsyslog.d folder for extra configuration files"
mkdir -p /opt/local/etc/rsyslog.d

# Get acmetool for Let's Encrypt certificates
echo "* Install Let's Encrypt certificates"
acmetool_version=v0.0.62
curl -LO https://github.com/hlandau/acme/releases/download/${acmetool_version}/acmetool-${acmetool_version}-solaris_amd64.tar.gz && tar xvzf acmetool-${acmetool_version}-solaris_amd64.tar.gz
cd acmetool-${acmetool_version}-solaris_amd64
cp bin/acmetool /opt/local/bin/acmetool.real
cd ..
rm -rf acmetool-${acmetool_version}-solaris_amd64.tar.gz acmetool-${acmetool_version}-solaris_amd64

echo "* Activate munin plugins"
/opt/local/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm -rf /root/*
rm -rf /tmp/*

# Prepare image for provisioning
sm-prepare-image -y
